# Generated by Django 5.1.7 on 2025-03-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('capital', models.CharField(blank=True, max_length=500, null=True)),
                ('currencies', models.JSONField(blank=True, default=dict, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
                ('subregion', models.CharField(blank=True, max_length=500, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('continents', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
