# Generated by Django 5.1.7 on 2025-03-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
