# Generated by Django 5.1.7 on 2025-03-28 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_country_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
